version: '3'

services:
  mongodb:
    container_name: ${DB_CONTAINER_NAME}
    image: "mongodb/mongodb-community-server"
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "27017:27017"